#!/bin/bash

# Partitioning: 1 x 1 GB EFI partition, the rest is root.

echo "Did you connect to the internet? (y/n)"
read internet

if [[ $internet = 'n' ]]; then
    exit 1
fi

echo "Which computer (desktop/x1-carbon/legion)?"
read comp

drivers="zan-arch-install/packages/drivers/$comp.txt"

if [[ $comp != 'desktop' ]] && [[ $comp != 'x1-carbon' ]] && [[ $comp != 'legion' ]]; then
    echo "Computer not supported. Exiting..."
    exit 1
fi

echo "EFI system partition: (ex. /dev/sda1p0 or /dev/nvme0n1p1)"
read bootpart

echo "Root partition: (ex. /dev/sda0p1 or /dev/nvme0n0)"
read rootpart

pswd=''

while [[ -z "$pswd" ]]; do
    echo "Enter password:"
    read pswd1

    echo "Reenter password:"
    read pswd2

    if [[ "$pswd1" != "$pswd2" ]]; then
	echo "Passwords don't match."
    else
	pswd="$pswd1"
    fi
done

mkfs.ext4 "$rootpart"

mount "$rootpart" /mnt
mount --mkdir "$bootpart" /mnt/efi

pacstrap -K /mnt $(cat zan-arch-install/packages/base.txt "$drivers" | tr '\n' ' ')

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt <<EOF
# Locale set up
ln -sf /usr/share/zoneinfo/Canada/Mountain /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Network Manager config
echo "$comp" > /etc/hostname
systemctl enable NetworkManager.service

# Set up user and passwords
echo "root:$pswd" | chpasswd
useradd -m zan
echo "zan:$pswd" | chpasswd

# Set up GRUB
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=grub
echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

# Get zan-arch-install downloaded.
git clone https://github.com/DanZanzibar/zan-arch-install.git /home/zan/zan-arch-install
EOF

# Finishing up.
echo "Installation complete! Things to do after reboot:"
echo "  1. Check that sudo is working and 'zan' added to sudoers file using 'EDITOR=emacs visudo'."
echo "  2. Get connected to internet via 'nmcli device wifi connect NETWORK_NAME'."
echo "  3. Run 'sudo zan-arch-install/post-install'."
echo "  4. Run 'sudo grub-mkconfig -o /boot/grub/grub.cfg' again to detect Windows bootloaders."

umount -R /mnt
reboot

