#!/usr/bin/env bash

# Install packages
sudo pacman -Syu
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/gui.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/audio.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/network.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/programming.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/others.txt

# Enable systemd system services
sudo systemctl enable bluetooth.service
sudo systemctl start bluetooth.service

sudo systemctl enable sshd.service
sudo systemctl start sshd.service

sudo systemctl enable systemd-timesyncd.service
sudo systemctl start systemd-timesyncd.service

# Enable systemd user services.
systemctl --user enable pulseaudio.service
systemctl --user start pulseaudio.service

systemctl --user enable syncthing.service
systemctl --user start syncthing.service

# Get dot files.
git clone https://github.com/DanZanzibar/dotfiles.git
source ~/dotfiles/.bashrc

# Symlink config files.
~/zan-arch-install/scripts/symlink.py 

# Chrome
mkdir ~/builds
cd ~/builds/
git clone https://aur.archlinux.org/google-chrome.git
cd ~/builds/google-chrome/
makepkg -si
cd

# Emacs set up.
cd ~/.emacs.d/
git clone https://github.com/DanZanzibar/zan-emacs.git
ln -s zan-emacs/init.el
cd

# Set up Github auth.
gh auth login

# Clean up.
sudo rm -rf ~/zan-arch-install

echo "Check dotfiles/backup to see what config files were replaced."
