#!/usr/bin/env bash

# Install packages
pacman -Syu
pacman -S --noconfirm - < zan-arch-install/packages/gui.txt
pacman -S --noconfirm - < zan-arch-install/packages/audio.txt
pacman -S --noconfirm - < zan-arch-install/packages/network.txt

# Systemd enabling for system services
systemctl enable bluetooth.service
systemctl enable sshd.service

# Enable systemd user services
systemctl --user enable pulseaudio.service
systemctl --user enable syncthing.service
systemctl --user start pulseaudio.service
systemctl --user start syncthing.service

git clone https://github.com/DanZanzibar/dotfiles.git
source /home/zan/dotfiles/.bashrc

mkdir /etc/X11/xorg.conf.d
for file in /home/zan/dotfiles/xorg.conf.d/*; do
    ln -s -t /etc/X11/xorg.conf.d/ "/home/zan/dotfiles/xorg.conf.d/$file"
done

ln -sf -t . /home/zan/dotfiles/.bashrc /home/zan/dotfiles/.gitconfig /home/zan/dotfiles/.xinitrc /home/zan/dotfiles/.xbindkeysrc

if [[ "$HOSTNAME" != 'desktop' ]]; then
    ln -sf -t . /home/zan/dotfiles/x1-carbon/.Xresources 
fi

mkdir /home/zan/.config
rm -r /home/zan/.config/polybar /home/zan/.config/autorandr /home/zan/.config/Zeal
ln -s -t /home/zan/.config /home/zan/dotfiles/polybar /home/zan/dotfiles/Zeal

mkdir /home/zan/.config/herbstluftwm 
ln -sf -t /home/zan/.config/herbstluftwm /home/zan/dotfiles/herbstluftwm/autostart /home/zan/dotfiles/herbstluftwm/scripts/

ln -s -t /home/zan/.config "/home/zan/dotfiles/$HOSTNAME/autorandr"
ln -s -t /home/zan/.config/herbstluftwm "/home/zan/dotfiles/$HOSTNAME/layouts"
