#!/usr/bin/env bash

# Install more packages.
sudo ~/zan-arch-install/post-install-1-root

# Enable systemd user services.
systemctl --user enable pulseaudio.service
systemctl --user enable syncthing.service
systemctl --user start pulseaudio.service
systemctl --user start syncthing.service

# Get dot files.
git clone https://github.com/DanZanzibar/dotfiles.git
source ~/dotfiles/.bashrc

# Symlink config files.
~/zan-arch-install/symlinking

# Chrome
mkdir ~/builds
cd ~/builds/
git clone https://aur.archlinux.org/google-chrome.git
cd ~/builds/google-chrome/
makepkg -si

# Set up Github auth.
gh auth login

# Emacs and language server set up.


# Clean up.
sudo rm -rf ~/zan-arch-install
