#!/usr/bin/env bash

install_notes="~/install-notes.txt"

# Install packages
sudo pacman -Syu
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/gui.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/audio.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/network.txt
sudo pacman -S --noconfirm - < ~/zan-arch-install/packages/programming.txt 

# Enable systemd system services
sudo systemctl enable bluetooth.service
sudo systemctl enable sshd.service

# Enable systemd user services.
systemctl --user enable pulseaudio.service
systemctl --user enable syncthing.service
systemctl --user start pulseaudio.service
systemctl --user start syncthing.service

# Get dot files.
git clone https://github.com/DanZanzibar/dotfiles.git
source ~/dotfiles/.bashrc

# Symlink config files.
~/zan-arch-install/symlink-dotfiles

# Chrome
mkdir ~/builds
cd ~/builds/
git clone https://aur.archlinux.org/google-chrome.git
cd ~/builds/google-chrome/
makepkg -si

# Set up Github auth.
gh auth login

# Emacs and language server set up.


# Clean up.
sudo rm -rf ~/zan-arch-install

echo "Check dotfiles/backup to see what config files were replaced."
