#!/usr/bin/env bash

# Install packages
pacman -Syu
pacman -S --noconfirm - < ~/zan-arch-install/packages/gui.txt
pacman -S --noconfirm - < ~/zan-arch-install/packages/audio.txt
pacman -S --noconfirm - < ~/zan-arch-install/packages/network.txt
pacman -S --noconfirm - < ~/zan-arch-install/packages/programming.txt 

# Systemd enabling for system services
systemctl enable bluetooth.service
systemctl enable sshd.service
