#!/usr/bin/env bash

export backups=~/dotfiles/backup

# Symlinks for xorg conf files.
sudo -E ~/zan-arch-install/scripts/symlink-files-in-dir ~/dotfiles/xorg.conf.d/ /etc/X11/xorg.conf.d/

# Symlinks for home directory dot files.
~/zan-arch-install/scripts/symlink-files-in-dir ~/dotfiles/home/ ~

# Symlink '.Xresources' for high DPI screens.
if [[ -f ~/dotfiles/"$HOSTNAME"/.Xresources ]]; then
    ~/zan-arch-install/scripts/symlink ~/dotfiles/"$HOSTNAME"/.Xresources ~
fi

# Symlinks for '.config'.
if [[ ! -d ~/.config ]]; then
    mkdir ~/.config
fi
~/zan-arch-install/scripts/symlink-files-in-dir ~/dotfiles/config/ ~/.config/
~/zan-arch-install/scripts/symlink ~/dotfiles/"$HOSTNAME"/autorandr ~/.config/

# Symlink for herbstluftwm 'autostart'.
if [[ ! -d ~/.config/herbstluftwm ]]; then
    mkdir ~/.config/herbstluftwm
fi
~/zan-arch-install/scripts/symlink ~/dotfiles/herbstluftwm/autostart ~/.config/herbstluftwm/
