#!/usr/bin/env bash

if [[ -z "$backups" || ! -d "$backups" ]]; then
    echo "Error: backups directory is not set or does not exist."
    exit 1
fi

if [[ ! -e "$1" ]]; then
    echo "Error: Source $1 does not exist."
    exit 1
fi

if [[ ! -d "$2" ]]; then
    echo "Error: Target directory $2 does not exist."
    exit 1
fi

link="$2/$(basename "$1")"

if [[ -e "$link" ]]; then
    if [[ -h "$link" ]]; then
	echo "Removing old link: $link"
	rm "$link"
    else
	echo "Backing up: $link"
	mv "$link" "$backups"
    fi
fi

ln -s -t "$2" "$1"
